# atril
# Autogenerated from man page /usr/share/man/man1/atril.1.gz
complete -c atril -s p -l page-label --description 'Here you can specify a page label, this page will be selected in the document…'
complete -c atril -s i -l page-index --description 'Here you can specify a page number, this page will be selected in the documen…'
complete -c atril -s f -l fullscreen --description 'Start atril in fullscreen mode.'
complete -c atril -s s -l presentation --description 'Start atril in presentation mode.'
complete -c atril -s w -l preview --description 'Start atril in preview mode.'
complete -c atril -l display --description 'X display to use.'
complete -c atril -l version --description 'Output version information and exit.'
complete -c atril -s '?' -s h -l help --description 'Print standard command line options.'

