# delv
# Autogenerated from man page /usr/share/man/man1/delv.1.gz
complete -c delv -s a --description 'This option specifies a file from which to read DNSSEC trust anchors.'
complete -c delv -s b --description 'This option sets the source IP address of the query to address.'
complete -c delv -s c --description 'This option sets the query class for the requested data.'
complete -c delv -s d --description 'This option sets the systemwide debug level to level.'
complete -c delv -s h --description 'This option displays the delv help usage output and exits.'
complete -c delv -s i --description 'This option sets insecure mode, which disables internal DNSSEC validation.'
complete -c delv -s m --description 'This option enables memory usage debugging.'
complete -c delv -s p --description 'This option specifies a destination port to use for queries, instead of the s…'
complete -c delv -s q --description 'This option sets the query name to name.'
complete -c delv -s t --description 'This option sets the query type to type, which can be any valid query type su…'
complete -c delv -s v --description 'This option prints the delv version and exits.'
complete -c delv -s x --description 'This option performs a reverse lookup, mapping an address to a name.'
complete -c delv -s 4 --description 'This option forces delv to only use IPv4.'
complete -c delv -s 6 --description 'This option forces delv to only use IPv6.'

