# dtplite
# Autogenerated from man page /usr/share/man/man1/dtplite.1.gz
complete -c dtplite -s o --description 'This is the form for use case [1].'
complete -c dtplite -o merge --description 'This is the form for use case [3].'
complete -c dtplite -o exclude --description 'This option specifies an exclude (glob) pattern.'
complete -c dtplite -o ext --description 'If the name of an output file has to be derived from the name of an input fil…'
complete -c dtplite -o header --description 'This option can be used if and only if the selected format provides an engine…'
complete -c dtplite -o footer --description 'Like -header, except that: Any navigation buttons are ignored, the correspond…'
complete -c dtplite -o style --description 'This option can be used if and only if the selected format provides an engine…'
complete -c dtplite -o toc --description 'This option specifies a doctoc file to use for the table of contents instead …'
complete -c dtplite -o pre+toc --description '.'
complete -c dtplite -o post+toc --description 'This option specifies additional doctoc files (or texts) to use in the naviga…'
complete -c dtplite -o prenav -o postnav --description '.'
complete -c dtplite -o nav --description '.'

