# nns
# Autogenerated from man page /usr/share/man/man1/nns.1.gz
complete -c nns -o host --description 'If this option is not specified it defaults to localhost.'
complete -c nns -o port --description 'If this option is not specified it defaults to 38573.'

