# nnsd
# Autogenerated from man page /usr/share/man/man1/nnsd.1.gz
complete -c nnsd -o localonly --description 'If this option is not specified it defaults to true, i. e.'
complete -c nnsd -o port --description 'If this option is not specified it defaults to 38573.'

