# pppoe-discovery
# Autogenerated from man page /usr/share/man/man8/pppoe-discovery.8.gz
complete -c pppoe-discovery -s I --description 'RS The -I option specifies the Ethernet interface to use.'
complete -c pppoe-discovery -s D --description 'RS The -D option causes every packet to be dumped to the specified file_name.'
complete -c pppoe-discovery -s U --description 'RS Causes pppoe-discovery to use the Host-Uniq tag in its discovery packets.'
complete -c pppoe-discovery -s W --description 'RS Causes pppoe-discovery to use the Host-Uniq tag in its discovery packets.'
complete -c pppoe-discovery -s S --description 'RS Specifies the desired service name.'
complete -c pppoe-discovery -s C --description 'RS Specifies the desired access concentrator name.'
complete -c pppoe-discovery -s Q --description 'RS Causes pppoe-discovery to avoid printing discovered access concentrator na…'
complete -c pppoe-discovery -s t --description 'RS Changes the discovery timeout for PADI requests, in seconds.'
complete -c pppoe-discovery -s a --description 'RS Changes the number of PADI discovery attempts made.'
complete -c pppoe-discovery -s V -s h --description '.'

