# qterminal
# Autogenerated from man page /usr/share/man/man1/qterminal.1.gz
complete -c qterminal -s d -l drop --description 'Start in "dropdown mode" (like Yakuake or Tilda).'
complete -c qterminal -s e -l execute --description 'Execute command instead of shell.'
complete -c qterminal -s h -l help --description 'Print this help.'
complete -c qterminal -s p -l profile --description 'Load qterminal with specific options.'
complete -c qterminal -s v -l version --description 'Prints application version and exits.'
complete -c qterminal -s w -l workdir --description 'Start session with specified work directory.'

