# tcldocstrip
# Autogenerated from man page /usr/share/man/man1/tcldocstrip.1.gz
complete -c tcldocstrip -o guards --description 'This is the form for use case [3].'
complete -c tcldocstrip -o metaprefix --description 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o onerror --description 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o trimlines --description 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o preamble --description '.'
complete -c tcldocstrip -o postamble --description '.'
complete -c tcldocstrip -o nopreamble --description '.'
complete -c tcldocstrip -o nopostamble --description 'The -no*amble options deactivate file pre- and postambles altogether, whereas…'

