# thunar
# Autogenerated from man page /usr/share/man/man1/thunar.1.gz
complete -c thunar -l bulk-rename --description 'option is specified no file managers windows will be opened, but instead the …'
complete -c thunar -s '?' -l help --description '.'
complete -c thunar -s V -l version --description '.'
complete -c thunar -s B --description '.'
complete -c thunar -l daemon --description '.'
complete -c thunar -l display --description '.'
complete -c thunar -s q -l quit --description '.'

