# tune
# Autogenerated from man page /usr/share/man/man8/tune.exfat.8.gz
complete -c tune -s l --description 'Print the volume label of the exFAT filesystem.'
complete -c tune -s L --description 'Set the volume label of the filesystem to the provided argument.'
complete -c tune -s i --description 'Print the volume serial of the exFAT filesystem.'
complete -c tune -s I --description 'Set the volume serial of the filesystem to the provided argument.'
complete -c tune -s v --description 'Prints verbose debugging information while extracting or tuning parameters of…'
complete -c tune -s V --description 'Prints the version number and exits.'

