# xfce4-sensors
# Autogenerated from man page /usr/share/man/man1/xfce4-sensors.1.gz
complete -c xfce4-sensors -s h -l help --description 'Print this help dialog.'
complete -c xfce4-sensors -s l -l license --description '.'
complete -c xfce4-sensors -s v -l version --description '.'

