# xfce4-popup-places
# Autogenerated from man page /usr/share/man/man1/xfce4-popup-places.1.gz
complete -c xfce4-popup-places -s p -l pointer --description 'Popup menu at current mouse position.'
complete -c xfce4-popup-places -s h -l help --description 'Show help options.'
complete -c xfce4-popup-places -s V -l version --description 'Print version information and exit COPYRIGHT Copyright © 2004-2011 The Xfce d…'

