# xiccd
# Autogenerated from man page /usr/share/man/man8/xiccd.8.gz
complete -c xiccd -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c xiccd -s V -l version --description 'Show version.'
complete -c xiccd -s d -l display --description 'X server to contact.'
complete -c xiccd -s e -l edid --description 'Generate profiles by monitor EDID AUTHORS xiccd was primarily written by Alex…'

